spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sfb_prod
    username: sfb_prod_user
    password: blue
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: false